"""added is_admin to tenant

Revision ID: e1cd458b002c
Revises: 5846e87c7731
Create Date: 2026-02-27 01:12:39.902757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1cd458b002c'
down_revision = '5846e87c7731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant')
    op.drop_table('customer')
    op.drop_table('service')
    op.drop_table('queue')
    op.drop_table('appointment')
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('schedule',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('staff_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('staff_tenant_id_fkey'), 'tenant', ['tenant_id'], ['id'])
        batch_op.alter_column('schedule',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    op.create_table('appointment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('staff_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('appointment_customer_id_fkey')),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], name=op.f('appointment_service_id_fkey')),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('appointment_staff_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('appointment_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('appointment_pkey'))
    )
    op.create_table('queue',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estimated_wait', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('customer_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('queue_customer_id_fkey')),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], name=op.f('queue_service_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('queue_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('queue_pkey'))
    )
    op.create_table('service',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('service_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('service_pkey'))
    )
    op.create_table('customer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('visits', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('customer_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('customer_pkey')),
    sa.UniqueConstraint('tenant_id', 'phone', name=op.f('unique_customer_phone'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('tenant',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('subdomain', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('owner_email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tenant_pkey')),
    sa.UniqueConstraint('name', name=op.f('tenant_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('owner_email', name=op.f('tenant_owner_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('subdomain', name=op.f('tenant_subdomain_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
